== Stormpot

Stormpot is an object pooling library for Java.
Use it to recycle objects that are expensive to create.
The library will take care of creating and destroying your objects in the
background.

image:https://api.travis-ci.org/chrisvest/stormpot.svg?branch=master[Build status, link=https://travis-ci.org/chrisvest/stormpot]
image:https://img.shields.io/lgtm/grade/java/g/chrisvest/stormpot.svg?logo=lgtm&logoWidth=18[Code quality, link=https://lgtm.com/projects/g/chrisvest/stormpot/context:java]
image:https://codecov.io/gh/chrisvest/stormpot/branch/master/graph/badge.svg[Code coverage, link=https://codecov.io/gh/chrisvest/stormpot]

Stormpot is very mature, is used in production, and has done hundreds of
trillions footnote:[Fermi estimate.] claim-release cycles in testing.
It is faster and scales better than any competing pool.

 * Home page: http://chrisvest.github.io/stormpot/
 * Source code: https://github.com/chrisvest/stormpot/
 * API docs: http://chrisvest.github.io/stormpot/site/apidocs/index.html
 * Mailing list: http://groups.google.com/d/forum/stormpot
 * License: http://www.apache.org/licenses/LICENSE-2.0.html[The Apache Software
   License 2.0]
 * Simple versioning: X.Y where Y{plus}{plus} is backwards compatible, and
   X{plus}{plus} is backwards incompatible.

=== Why choose Stormpot?

There are a number of options out there, when it comes to object pools on the
JVM. Stormpot has been carefully designed for high performance, and robust
operation. Some of the things that sets Stormpot apart include:

 * Business friendly http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2
   license].
 * Very high http://chrisvest.github.io/stormpot/site/jacoco/index.html[test
   coverage].
 * The https://medium.com/@chrisvest/released-stormpot-2-1-c31509142757[highest
   throughput and lowest latency] in its class.
   (since 2.1)
 * https://medium.com/@chrisvest/released-stormpot-2-2-ccd1e8639f07[Automatic
   recovery] from sporadic backend (Allocator) failures.
   (since 2.2)
 * Precise object leak detection with virtually no overhead.
   (since 2.3)
 * Optional background object expiration checking.
   (since 2.3)
 * Explicit object expiration.
   (since 2.4)
 * Gradual back-off for prolonged allocation failures.
   (since 3.0)
 * Support for Java Platform Module system.
   (since 3.0)
 * Support for a directly-allocating thread-less mode, via `Pool.of(...)`.
   (since 3.0)
 * Convenient lambda-based API.
   (since 3.0)
 * Control over the thread-local caching mechanics, via ``PoolTap``s.
   (since 3.0)
 * And other features that makes for a smooth runtime behaviour.

=== Installing

Stormpot 3.0 only depends on Java 11 or newer.
Add it as a Maven dependency to your projects:

[source,xml]
----
<dependency>
  <groupId>com.github.chrisvest</groupId>
  <artifactId>stormpot</artifactId>
  <version>3.0</version>
</dependency>
----

You can also build the latest snapshot from source with `mvn clean install`.
Note that the next version, Stormpot 3.0, will require Java 11, so you need this
version of Java to build a snapshot from the source code.

=== Getting Started

Stormpot needs 3 things before it can pool objects for you:

 . A http://chrisvest.github.io/stormpot/site/apidocs/stormpot/stormpot/Poolable.html[Poolable] type of objects it can pool.
   You have to implement this yourself.
 . An http://chrisvest.github.io/stormpot/site/apidocs/stormpot/stormpot/Allocator.html[Allocator] to allocate and deallocate the Poolable objects.
   You have to implement this yourself.
 . And a place where it all comes together:

[source,java]
----
MyAllocator allocator = new MyAllocator();
Pool<MyPoolable> pool = Pool.from(allocator).build();
Timeout timeout = new Timeout(1, TimeUnit.SECONDS);

MyPoolable object = pool.claim(timeout);
try {
  // Do stuff with 'object'.
  // Note: 'claim' returns 'null' if it times out.
} finally {
  if (object != null) {
    object.release();
  }
}
----

=== Contributing

 * *Report bugs* preferably with a failing test. You can submit a pull-request
   that adds a failing test that demonstrates the behaviour you think is wrong
   or missing. Travis-CI will build it, report the failure and shorten the
   feedback cycle. If you don't know how to write a test for something, then
   that's fine too. Just open an issue describing your configuration and
   environment, what you observe, and what you think should happen instead.
 * *Improve the documentation* by all means! Just fork the project and start.
   If you have questions about implementation or behavioural details, then start
   a discussion about it by opening a pull-request or an issue. Documentation
   and javadoc is formatted with http://asciidoctor.org/[AsciiDoctor].
   The website and javadocs can be generated with
   `mvn clean pre-site javadoc:javadoc`.
 * *Fix bugs or implement features* by forking the project, but please start an
   issue about the bug or feature you want to work on (or find the existing
   issue) and describe the approach and design you have in mind. Keep in mind
   that Stormpot is implemented with a very strict adherence to TDD.
   Finally, make sure to respect the existing indentation and formatting.
   Use `mvn checkstyle:check` to check your formatting.
   If you are writing a test that takes more than a few hundred milliseconds to
   run, then put it in the `stormpot.slow` test package; either in the existing
   `PoolIT` suite, or in a new `\*IT` suite.
   Use `mvn clean test` to run only the fast tests. Use `mvn clean verify` to
   also run the slow tests. Javadoc comments are formatted with
   http://asciidoctor.org/[AsciiDoctor].
   Get test coverage with `mvn clean test site` and
   `open target/site/jacoco/index.html`. Get mutation test coverage with
   `mvn clean test-compile org.pitest:pitest-maven:mutationCoverage` and
   `open target/pit-reports/*/index.html`.
 * *Update* Maven plugins with `mvn versions:display-plugin-updates`, or other
   dependencies with `versions:display-dependency-updates`.
 * *Add to the ecosystem* and make Stormpot more than just an object pool.
   This is a good thing to take on if you'd like to contribute code, but you
   find the Stormpot code base itself to be intimidating (which, by the way, I
   completely understand).
   ** There is a repository for
      https://github.com/chrisvest/object-pool-benchmarks[object pool benchmarks]
      that is being maintained along side Stormpot.
      Adding more benchmarks and cases; analysing results; trying out
      optimisations.
      These are all useful things to do.
   ** I started working on a
      https://github.com/chrisvest/stormpot-jdbc[JDBC connection pool]
      based on Stormpot, but the project has stagnated.
      It is no doubt a useful thing to have, though.
      If you want to take on that problem, either with offset in the existing
      code or by starting over from scratch, then please go ahead.
   ** I'm sure there are other interesting related problems out there to take on.
      There are many database drivers for various NoSQL databases, that have
      object pooling needs.

Whatever you decide to do, don't hesitate to ask questions on the mailing list
or on github if you have doubts or get stuck.
