= Stormpot

Stormpot is an object pooling library for Java. Use it to recycle objects that
are expensive to create. The library will take care of creating and destroying
your objects in the background. Stormpot is very mature, is used in production,
and has done over a trillion footnote:[Fermi estimate. The benchmark that
produced the charts for the 2.1 release blog post accounts for about 400 billion
of those cycles.] claim-release cycles in testing.

 * Home page: http://chrisvest.github.io/stormpot/
 * API docs: http://chrisvest.github.io/stormpot/site/apidocs/index.html
 * Mailing list: http://groups.google.com/d/forum/stormpot
 * License: http://www.apache.org/licenses/LICENSE-2.0.html[The Apache Software License 2.0]
 * Simple versioning: X.Y where Y\++ is backwards compatible, and X++ is
   backwards incompatible.


== Why choose Stormpot?

There are a number of options out there, when it comes to object pools on the
JVM. Stormpot has been carefully designed for high performance, and robust
operation. Some of the things that sets Stormpot apart include:

 * Business friendly http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2
   license].
 * Very high http://chrisvest.github.io/stormpot/site/jacoco/index.html[test
   coverage].
 * The http://chrisvest.name/released-stormpot-21.html[highest throughput and
   lowest latency] in its class.
 * http://chrisvest.name/released-stormpot-22.html[Automatic recovery] from
   sporadic backend (Allocator) failures.
 * And other features that makes for a smooth runtime behaviour.

== Installing

Stormpot only depends on Java 6 or newer. Add it as a Maven dependency to your
projects:

[source,xml]
--
<dependency>
  <groupId>com.github.chrisvest</groupId>
  <artifactId>stormpot</artifactId>
  <version>2.2</version>
</dependency>
--

You can also build the latest snapshot from source with +mvn clean install+.

== Getting started

Stormpot needs 3 things before it can pool objects for you:

 . A http://chrisvest.github.io/stormpot/site/apidocs/stormpot/Poolable.html[Poolable] type of objects it can pool. You have to implement this yourself.
 . An http://chrisvest.github.io/stormpot/site/apidocs/stormpot/Allocator.html[Allocator] to allocate and deallocate the Poolable objects. You have to implement this
   yourself.
 . And a place where it all comes together:

[source,java]
--
MyAllocator allocator = new MyAllocator();
Config<MyPoolable> config = new Config<MyPoolable>().setAllocator(allocator);
Pool<MyPoolable> pool = new BlazePool<MyPoolable>(config);
Timeout timeout = new Timeout(1, TimeUnit.SECONDS);

MyPoolable object = pool.claim(timeout);
try {
  // Do stuff with 'object'.
  // Note: 'claim' returns 'null' if it timed out.
} finally {
  if (object != null) {
    object.release();
  }
}
--

== Contributing

 * *Report bugs* preferably with a failing test. You can submit a pull-request
   that adds a failing test that demonstrates the behaviour you think is wrong
   or missing. Travis-CI will build it, report the failure and shorten the
   feedback cycle. If you don't know how to write a test for something, then
   that's fine too. Just open an issue describing your configuration and
   environment, what you observe, and what you think should happen instead.
 * *Improve the documentation* by all means! Just fork the project and start.
   If you have questions about implementation or behavioural details, then start
   a discussion about it by opening a pull-request or an issue. Documentation
   and javadoc is formatted with http://asciidoctor.org/[AsciiDoctor].
 * *Fix bugs or implement features* by forking the project, but please start an
   issue about the bug or feature you want to work on (or find the existing
   issue) and describe the approach and design you have in mind. Keep in mind
   that Stormpot is implemented with a very
   http://chrisvest.name/contract-coverage.html[strict adherence to TDD].
   Finally, make sure to respect the existing indentation and formatting.
   If you are writing a test that takes more than a few hundred milliseconds to
   run, then put it in the +stormpot.slow+ test package; either in the existing
   +PoolIT+ suite, or in a new +*IT+ suite.
   Use +mvn clean test+ to run only the fast tests. Use +mvn clean verify+ to
   also run the slow tests. Javadoc comments are formatted with
   http://asciidoctor.org/[AsciiDoctor].
   Get test coverage with +mvn clean test site+ and
   +open target/site/jacoco/index.html+. Get mutation test coverage with
   +mvn clean test-compile org.pitest:pitest-maven:mutationCoverage+ and
   +open target/pit-reports/*/index.html+.
