== Performance

Stormpot is fast.
Very fast.
However, there are a number of configurations and decisions, where you have to make the right choice, if you want to get the most out of it.

That said, you mustn't forget the number one rule of performance optimisation: measurement and analysis is king.

=== Considerations for Custom Expiration Implementations

The Expiration is one of the most performance critical components of the pool.
The `hasExpired` method is called at least once for every call to the `claim` method, and may be called several times if objects turn out to have expired.
It is therefore important for the performance of the pool, that the expiration check is as fast as possible.

This can be a challenge if, for instance, you are pooling database connections, and you are checking their validity by running a query.
The only way to make an operation faster, is by having it do less work.
One way to take this to heart, is by not doing the expensive part of the check – by not sending the validation query – on _every_ check, but only when it's been a while since the object was last checked.
Essentially, we want to amortise the cost of the expensive check.

One way we can accomplish this, is by pessimistically expiring objects after they have been live for only a short while, like a few seconds, for instance, depending on how much activity the pool is exposed to.
Then have the pool be configured with a `Reallocator` that does the expensive check in its `reallocate` method, and returns the object back into the pool if it hadn't expired after all.

A less elaborate amortisation mechanism can be built, by storing a re-check deadline in the `stamp` of the `SlotInfo`.
Then you just have to check if the current time is greater than the stamp, and if so, do the expensive check and put a new deadline in the stamp.
