== Performance

Stormpot is fast.
Very fast.
However, there are a number of configurations and decisions, where you have to make the right choice, if you want to get the most out of it.

That said, you mustn't forget the number one rule of performance optimisation: measurement is king.

=== Choosing the Right Pool Implementation

Stormpot comes with two Pool implementations, QueuePool and BlazePool, and BlazePool is generally the right choice.

The BlazePool implementation is faster in most cases, but not in all.
In particular, if the thread that claims an object is always different from the thread that releases it – a use case that is allowed, though discouraged – then the QueuePool will probably perform better than BlazePool.
I say probably, because it is not guaranteed to be the case.
BlazePool has a single-element thread-local cache, where it stores the object most recently claimed by the given thread.
If this object happens to be available, then it will be claimed in preference to all the other objects in the pool.
This means that if the releasing thread can release the object before the claimer thread wants to claim another object, then the magic of the thread-local cache will apply, and BlazePool will most likely perform better than QueuePool.

=== Considerations for Custom Expiration Implementations

The Expiration is one of the most performance critical components of the pool.
The `hasExpired` method is called at least once for every call to the `claim` method, and may be called several times if objects turn out to have expired.
It is therefore important for the performance of the pool, that the expiration check is as fast as possible.

This can be a challenge if, for instance, you are pooling database connections, and you are checking their validity by running a query.
The only way to make an operation faster, is by having it do less work.
One way to take this to heart, is by not doing the expensive part of the check – by not sending the validation query – on _every_ check, but only when it's been a while since the object was last checked.
Essentially, we want to amortise the cost of the expensive check.

One way we can accomplish this, is by pessimistically expiring objects after they have been live for only a short while, like a few seconds, for instance, depending on how much activity the pool is exposed to.
Then have the pool be configured with a `Reallocator` that does the expensive check in its `reallocate` method, and returns the object back into the pool if it hadn't expired after all.

A less elaborate amortisation mechanism can be built, by storing a re-check deadline in the `stamp` of the `SlotInfo`.
Then you just have to check if the current time is greater than the stamp, and if so, do the expensive check and put a new deadline in the stamp.

=== Overriding the Default Queue Implementation

NOTE: The internals of how Stormpot implements blocking behaviour, and the fact that it uses queues under the hood, is implementation and version specific, and by no means guaranteed to work the same way in future versions.
This description is for version 2.3.

Stormpot uses `BlockingQueue` objects under the hood, to transfer objects between the user threads and the dedicated allocation thread, and to implement its blocking behaviour.
By default, it uses `j.u.c.LinkedTransferQueue` if it is available on the classpath, e.g. with Java 7 and beyond, but otherwise falls back to the `j.u.c.LinkedBlockingQueue`.
LTQ is often faster than LBQ, but not always.
Figuring out which one is most optimal requires careful measurement of their behaviour for your particular load and use case.

If you want to override the BlockingQueue implementation that Stormpot uses, can be done globally for all pool instances, by setting the `stormpot.blocking.queue.impl` system property on JVM startup.
For instance, to make Stormpot always use the LBQ implementation, you can add an `-Dstormpot.blocking.queue.impl=java.util.concurrent.LinkedBlockingQueue` argument to the `java` command invocation.
Note that Stormpot expects the configured class to have a no-arguments constructor, and implement the `BlockingQueue` interface.
